/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [7-1:0] M_ge_target_out;
  wire [7-1:0] M_ge_current_out;
  wire [3-1:0] M_ge_btn_a;
  wire [3-1:0] M_ge_btn_b;
  wire [3-1:0] M_ge_btn_c;
  wire [3-1:0] M_ge_btn_d;
  reg [5-1:0] M_ge_btn;
  game_engine_2 ge (
    .clk(clk),
    .rst(rst),
    .btn(M_ge_btn),
    .target_out(M_ge_target_out),
    .current_out(M_ge_current_out),
    .btn_a(M_ge_btn_a),
    .btn_b(M_ge_btn_b),
    .btn_c(M_ge_btn_c),
    .btn_d(M_ge_btn_d)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'h0;
    io_seg = 8'h00;
    M_ge_btn[0+4-:5] = io_button[0+4-:5];
    io_led[0+0+6-:7] = M_ge_current_out[0+6-:7];
    io_led[8+0+2-:3] = M_ge_btn_a[0+2-:3];
    io_led[8+4+2-:3] = M_ge_btn_b[0+2-:3];
    io_led[16+0+2-:3] = M_ge_btn_c[0+2-:3];
    io_led[16+4+2-:3] = M_ge_btn_d[0+2-:3];
  end
endmodule
