/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module new_ge_2 (
    input clk,
    input [4:0] btn,
    output reg [6:0] target_out,
    output reg [6:0] current_out
  );
  
  
  
  reg [6:0] temp;
  
  wire [7-1:0] M_ram_out_number;
  reg [1-1:0] M_ram_location;
  reg [1-1:0] M_ram_state;
  reg [7-1:0] M_ram_in_number;
  ram_handler_3 ram (
    .clk(clk),
    .location(M_ram_location),
    .state(M_ram_state),
    .in_number(M_ram_in_number),
    .out_number(M_ram_out_number)
  );
  
  always @* begin
    M_ram_state = 1'h0;
    M_ram_location = 1'h0;
    current_out = M_ram_out_number;
    temp = M_ram_out_number;
    M_ram_in_number = 1'h0;
    target_out = 7'h63;
    if (btn[0+0-:1]) begin
      temp = temp + 2'h2;
      M_ram_state = 1'h1;
      M_ram_location = 1'h0;
      M_ram_in_number = temp;
    end
  end
endmodule
