/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lookuptable_1 (
    input [3:0] invalue_a,
    input [3:0] invalue_b,
    input [3:0] invalue_c,
    input [3:0] invalue_d,
    input [6:0] invalue_current,
    input [6:0] invalue_target,
    output reg [3:0] out_a,
    output reg [3:0] out_a1,
    output reg [3:0] out_b,
    output reg [3:0] out_b1,
    output reg [3:0] out_c,
    output reg [3:0] out_c1,
    output reg [3:0] out_d,
    output reg [3:0] out_d1,
    output reg [3:0] out_current,
    output reg [3:0] out_current1,
    output reg [3:0] out_target,
    output reg [3:0] out_target1
  );
  
  
  
  always @* begin
    
    case (invalue_a)
      1'h1: begin
        out_a = 4'h1;
        out_a1 = 4'h0;
      end
      2'h2: begin
        out_a = 4'h2;
        out_a1 = 4'h0;
      end
      2'h3: begin
        out_a = 4'h3;
        out_a1 = 4'h0;
      end
      3'h4: begin
        out_a = 4'h4;
        out_a1 = 4'h0;
      end
      3'h5: begin
        out_a = 4'h5;
        out_a1 = 4'h0;
      end
      3'h6: begin
        out_a = 4'h6;
        out_a1 = 4'h0;
      end
      3'h7: begin
        out_a = 4'h7;
        out_a1 = 4'h0;
      end
      4'h8: begin
        out_a = 4'h8;
        out_a1 = 4'h0;
      end
      4'h9: begin
        out_a = 4'h9;
        out_a1 = 4'h0;
      end
      4'ha: begin
        out_a = 4'h0;
        out_a1 = 4'h1;
      end
      4'hb: begin
        out_a = 4'h1;
        out_a1 = 4'h1;
      end
      4'hc: begin
        out_a = 4'h2;
        out_a1 = 4'h1;
      end
      4'hd: begin
        out_a = 4'h3;
        out_a1 = 4'h1;
      end
      4'he: begin
        out_a = 4'h4;
        out_a1 = 4'h1;
      end
      4'hf: begin
        out_a = 4'h5;
        out_a1 = 4'h1;
      end
      default: begin
        out_a = 4'h0;
        out_a1 = 4'h0;
      end
    endcase
    
    case (invalue_b)
      1'h1: begin
        out_b = 4'h1;
        out_b1 = 4'h0;
      end
      2'h2: begin
        out_b = 4'h2;
        out_b1 = 4'h0;
      end
      2'h3: begin
        out_b = 4'h3;
        out_b1 = 4'h0;
      end
      3'h4: begin
        out_b = 4'h4;
        out_b1 = 4'h0;
      end
      3'h5: begin
        out_b = 4'h5;
        out_b1 = 4'h0;
      end
      3'h6: begin
        out_b = 4'h6;
        out_b1 = 4'h0;
      end
      3'h7: begin
        out_b = 4'h7;
        out_b1 = 4'h0;
      end
      4'h8: begin
        out_b = 4'h8;
        out_b1 = 4'h0;
      end
      4'h9: begin
        out_b = 4'h9;
        out_b1 = 4'h0;
      end
      4'ha: begin
        out_b = 4'h0;
        out_b1 = 4'h1;
      end
      4'hb: begin
        out_b = 4'h1;
        out_b1 = 4'h1;
      end
      4'hc: begin
        out_b = 4'h2;
        out_b1 = 4'h1;
      end
      4'hd: begin
        out_b = 4'h3;
        out_b1 = 4'h1;
      end
      4'he: begin
        out_b = 4'h4;
        out_b1 = 4'h1;
      end
      4'hf: begin
        out_b = 4'h5;
        out_b1 = 4'h1;
      end
      default: begin
        out_b = 4'h0;
        out_b1 = 4'h0;
      end
    endcase
    
    case (invalue_c)
      1'h1: begin
        out_c = 4'h1;
        out_c1 = 4'h0;
      end
      2'h2: begin
        out_c = 4'h2;
        out_c1 = 4'h0;
      end
      2'h3: begin
        out_c = 4'h3;
        out_c1 = 4'h0;
      end
      3'h4: begin
        out_c = 4'h4;
        out_c1 = 4'h0;
      end
      3'h5: begin
        out_c = 4'h5;
        out_c1 = 4'h0;
      end
      3'h6: begin
        out_c = 4'h6;
        out_c1 = 4'h0;
      end
      3'h7: begin
        out_c = 4'h7;
        out_c1 = 4'h0;
      end
      4'h8: begin
        out_c = 4'h8;
        out_c1 = 4'h0;
      end
      4'h9: begin
        out_c = 4'h9;
        out_c1 = 4'h0;
      end
      4'ha: begin
        out_c = 4'h0;
        out_c1 = 4'h1;
      end
      4'hb: begin
        out_c = 4'h1;
        out_c1 = 4'h1;
      end
      4'hc: begin
        out_c = 4'h2;
        out_c1 = 4'h1;
      end
      4'hd: begin
        out_c = 4'h3;
        out_c1 = 4'h1;
      end
      4'he: begin
        out_c = 4'h4;
        out_c1 = 4'h1;
      end
      4'hf: begin
        out_c = 4'h5;
        out_c1 = 4'h1;
      end
      default: begin
        out_c = 4'h0;
        out_c1 = 4'h0;
      end
    endcase
    
    case (invalue_d)
      1'h1: begin
        out_d = 4'h1;
        out_d1 = 4'h0;
      end
      2'h2: begin
        out_d = 4'h2;
        out_d1 = 4'h0;
      end
      2'h3: begin
        out_d = 4'h3;
        out_d1 = 4'h0;
      end
      3'h4: begin
        out_d = 4'h4;
        out_d1 = 4'h0;
      end
      3'h5: begin
        out_d = 4'h5;
        out_d1 = 4'h0;
      end
      3'h6: begin
        out_d = 4'h6;
        out_d1 = 4'h0;
      end
      3'h7: begin
        out_d = 4'h7;
        out_d1 = 4'h0;
      end
      4'h8: begin
        out_d = 4'h8;
        out_d1 = 4'h0;
      end
      4'h9: begin
        out_d = 4'h9;
        out_d1 = 4'h0;
      end
      4'ha: begin
        out_d = 4'h0;
        out_d1 = 4'h1;
      end
      4'hb: begin
        out_d = 4'h1;
        out_d1 = 4'h1;
      end
      4'hc: begin
        out_d = 4'h2;
        out_d1 = 4'h1;
      end
      4'hd: begin
        out_d = 4'h3;
        out_d1 = 4'h1;
      end
      4'he: begin
        out_d = 4'h4;
        out_d1 = 4'h1;
      end
      4'hf: begin
        out_d = 4'h5;
        out_d1 = 4'h1;
      end
      default: begin
        out_d = 4'h0;
        out_d1 = 4'h0;
      end
    endcase
    
    case (invalue_current)
      1'h0: begin
        out_current = 4'h0;
        out_current1 = 4'h0;
      end
      1'h1: begin
        out_current = 4'h1;
        out_current1 = 4'h0;
      end
      2'h2: begin
        out_current = 4'h2;
        out_current1 = 4'h0;
      end
      2'h3: begin
        out_current = 4'h3;
        out_current1 = 4'h0;
      end
      3'h4: begin
        out_current = 4'h4;
        out_current1 = 4'h0;
      end
      3'h5: begin
        out_current = 4'h5;
        out_current1 = 4'h0;
      end
      3'h6: begin
        out_current = 4'h6;
        out_current1 = 4'h0;
      end
      3'h7: begin
        out_current = 4'h7;
        out_current1 = 4'h0;
      end
      4'h8: begin
        out_current = 4'h8;
        out_current1 = 4'h0;
      end
      4'h9: begin
        out_current = 4'h9;
        out_current1 = 4'h0;
      end
      4'ha: begin
        out_current = 4'h0;
        out_current1 = 4'h1;
      end
      4'hb: begin
        out_current = 4'h1;
        out_current1 = 4'h1;
      end
      4'hc: begin
        out_current = 4'h2;
        out_current1 = 4'h1;
      end
      4'hd: begin
        out_current = 4'h3;
        out_current1 = 4'h1;
      end
      4'he: begin
        out_current = 4'h4;
        out_current1 = 4'h1;
      end
      4'hf: begin
        out_current = 4'h5;
        out_current1 = 4'h1;
      end
      5'h10: begin
        out_current = 4'h6;
        out_current1 = 4'h1;
      end
      5'h11: begin
        out_current = 4'h7;
        out_current1 = 4'h1;
      end
      5'h12: begin
        out_current = 4'h8;
        out_current1 = 4'h1;
      end
      5'h13: begin
        out_current = 4'h9;
        out_current1 = 4'h1;
      end
      5'h14: begin
        out_current = 4'h0;
        out_current1 = 4'h2;
      end
      5'h15: begin
        out_current = 4'h1;
        out_current1 = 4'h2;
      end
      5'h16: begin
        out_current = 4'h2;
        out_current1 = 4'h2;
      end
      5'h17: begin
        out_current = 4'h3;
        out_current1 = 4'h2;
      end
      5'h18: begin
        out_current = 4'h4;
        out_current1 = 4'h2;
      end
      5'h19: begin
        out_current = 4'h5;
        out_current1 = 4'h2;
      end
      5'h1a: begin
        out_current = 4'h6;
        out_current1 = 4'h2;
      end
      5'h1b: begin
        out_current = 4'h7;
        out_current1 = 4'h2;
      end
      5'h1c: begin
        out_current = 4'h8;
        out_current1 = 4'h2;
      end
      5'h1d: begin
        out_current = 4'h9;
        out_current1 = 4'h2;
      end
      5'h1e: begin
        out_current = 4'h0;
        out_current1 = 4'h3;
      end
      5'h1f: begin
        out_current = 4'h1;
        out_current1 = 4'h3;
      end
      6'h20: begin
        out_current = 4'h2;
        out_current1 = 4'h3;
      end
      6'h21: begin
        out_current = 4'h3;
        out_current1 = 4'h3;
      end
      6'h22: begin
        out_current = 4'h4;
        out_current1 = 4'h3;
      end
      6'h23: begin
        out_current = 4'h5;
        out_current1 = 4'h3;
      end
      6'h24: begin
        out_current = 4'h6;
        out_current1 = 4'h3;
      end
      6'h25: begin
        out_current = 4'h7;
        out_current1 = 4'h3;
      end
      6'h26: begin
        out_current = 4'h8;
        out_current1 = 4'h3;
      end
      6'h27: begin
        out_current = 4'h9;
        out_current1 = 4'h3;
      end
      6'h28: begin
        out_current = 4'h0;
        out_current1 = 4'h4;
      end
      6'h29: begin
        out_current = 4'h1;
        out_current1 = 4'h4;
      end
      6'h2a: begin
        out_current = 4'h2;
        out_current1 = 4'h4;
      end
      6'h2b: begin
        out_current = 4'h3;
        out_current1 = 4'h4;
      end
      6'h2c: begin
        out_current = 4'h4;
        out_current1 = 4'h4;
      end
      6'h2d: begin
        out_current = 4'h5;
        out_current1 = 4'h4;
      end
      6'h2e: begin
        out_current = 4'h6;
        out_current1 = 4'h4;
      end
      6'h2f: begin
        out_current = 4'h7;
        out_current1 = 4'h4;
      end
      6'h30: begin
        out_current = 4'h8;
        out_current1 = 4'h4;
      end
      6'h31: begin
        out_current = 4'h9;
        out_current1 = 4'h4;
      end
      6'h32: begin
        out_current = 4'h0;
        out_current1 = 4'h5;
      end
      6'h33: begin
        out_current = 4'h1;
        out_current1 = 4'h5;
      end
      6'h34: begin
        out_current = 4'h2;
        out_current1 = 4'h5;
      end
      6'h35: begin
        out_current = 4'h3;
        out_current1 = 4'h5;
      end
      6'h36: begin
        out_current = 4'h4;
        out_current1 = 4'h5;
      end
      6'h37: begin
        out_current = 4'h5;
        out_current1 = 4'h5;
      end
      6'h38: begin
        out_current = 4'h6;
        out_current1 = 4'h5;
      end
      6'h39: begin
        out_current = 4'h7;
        out_current1 = 4'h5;
      end
      6'h3a: begin
        out_current = 4'h8;
        out_current1 = 4'h5;
      end
      6'h3b: begin
        out_current = 4'h9;
        out_current1 = 4'h5;
      end
      6'h3c: begin
        out_current = 4'h0;
        out_current1 = 4'h6;
      end
      6'h3d: begin
        out_current = 4'h1;
        out_current1 = 4'h6;
      end
      6'h3e: begin
        out_current = 4'h2;
        out_current1 = 4'h6;
      end
      6'h3f: begin
        out_current = 4'h3;
        out_current1 = 4'h6;
      end
      7'h40: begin
        out_current = 4'h4;
        out_current1 = 4'h6;
      end
      7'h41: begin
        out_current = 4'h5;
        out_current1 = 4'h6;
      end
      7'h42: begin
        out_current = 4'h6;
        out_current1 = 4'h6;
      end
      7'h43: begin
        out_current = 4'h7;
        out_current1 = 4'h6;
      end
      7'h44: begin
        out_current = 4'h8;
        out_current1 = 4'h6;
      end
      7'h45: begin
        out_current = 4'h9;
        out_current1 = 4'h6;
      end
      7'h46: begin
        out_current = 4'h0;
        out_current1 = 4'h7;
      end
      7'h47: begin
        out_current = 4'h1;
        out_current1 = 4'h7;
      end
      7'h48: begin
        out_current = 4'h2;
        out_current1 = 4'h7;
      end
      7'h49: begin
        out_current = 4'h3;
        out_current1 = 4'h7;
      end
      7'h4a: begin
        out_current = 4'h4;
        out_current1 = 4'h7;
      end
      7'h4b: begin
        out_current = 4'h5;
        out_current1 = 4'h7;
      end
      7'h4c: begin
        out_current = 4'h6;
        out_current1 = 4'h7;
      end
      7'h4d: begin
        out_current = 4'h7;
        out_current1 = 4'h7;
      end
      7'h4e: begin
        out_current = 4'h8;
        out_current1 = 4'h7;
      end
      7'h4f: begin
        out_current = 4'h9;
        out_current1 = 4'h7;
      end
      7'h50: begin
        out_current = 4'h0;
        out_current1 = 4'h8;
      end
      7'h51: begin
        out_current = 4'h1;
        out_current1 = 4'h8;
      end
      7'h52: begin
        out_current = 4'h2;
        out_current1 = 4'h8;
      end
      7'h53: begin
        out_current = 4'h3;
        out_current1 = 4'h8;
      end
      7'h54: begin
        out_current = 4'h4;
        out_current1 = 4'h8;
      end
      7'h55: begin
        out_current = 4'h5;
        out_current1 = 4'h8;
      end
      7'h56: begin
        out_current = 4'h6;
        out_current1 = 4'h8;
      end
      7'h57: begin
        out_current = 4'h7;
        out_current1 = 4'h8;
      end
      7'h58: begin
        out_current = 4'h8;
        out_current1 = 4'h8;
      end
      7'h59: begin
        out_current = 4'h9;
        out_current1 = 4'h8;
      end
      7'h5a: begin
        out_current = 4'h0;
        out_current1 = 4'h9;
      end
      7'h5b: begin
        out_current = 4'h1;
        out_current1 = 4'h9;
      end
      7'h5c: begin
        out_current = 4'h2;
        out_current1 = 4'h9;
      end
      7'h5d: begin
        out_current = 4'h3;
        out_current1 = 4'h9;
      end
      7'h5e: begin
        out_current = 4'h4;
        out_current1 = 4'h9;
      end
      7'h5f: begin
        out_current = 4'h5;
        out_current1 = 4'h9;
      end
      7'h60: begin
        out_current = 4'h6;
        out_current1 = 4'h9;
      end
      7'h61: begin
        out_current = 4'h7;
        out_current1 = 4'h9;
      end
      7'h62: begin
        out_current = 4'h8;
        out_current1 = 4'h9;
      end
      7'h63: begin
        out_current = 4'h9;
        out_current1 = 4'h9;
      end
      default: begin
        out_current = 4'h0;
        out_current1 = 4'h0;
      end
    endcase
    
    case (invalue_target)
      1'h0: begin
        out_target = 4'h0;
        out_target1 = 4'h0;
      end
      1'h1: begin
        out_target = 4'h1;
        out_target1 = 4'h0;
      end
      2'h2: begin
        out_target = 4'h2;
        out_target1 = 4'h0;
      end
      2'h3: begin
        out_target = 4'h3;
        out_target1 = 4'h0;
      end
      3'h4: begin
        out_target = 4'h4;
        out_target1 = 4'h0;
      end
      3'h5: begin
        out_target = 4'h5;
        out_target1 = 4'h0;
      end
      3'h6: begin
        out_target = 4'h6;
        out_target1 = 4'h0;
      end
      3'h7: begin
        out_target = 4'h7;
        out_target1 = 4'h0;
      end
      4'h8: begin
        out_target = 4'h8;
        out_target1 = 4'h0;
      end
      4'h9: begin
        out_target = 4'h9;
        out_target1 = 4'h0;
      end
      4'ha: begin
        out_target = 4'h0;
        out_target1 = 4'h1;
      end
      4'hb: begin
        out_target = 4'h1;
        out_target1 = 4'h1;
      end
      4'hc: begin
        out_target = 4'h2;
        out_target1 = 4'h1;
      end
      4'hd: begin
        out_target = 4'h3;
        out_target1 = 4'h1;
      end
      4'he: begin
        out_target = 4'h4;
        out_target1 = 4'h1;
      end
      4'hf: begin
        out_target = 4'h5;
        out_target1 = 4'h1;
      end
      5'h10: begin
        out_target = 4'h6;
        out_target1 = 4'h1;
      end
      5'h11: begin
        out_target = 4'h7;
        out_target1 = 4'h1;
      end
      5'h12: begin
        out_target = 4'h8;
        out_target1 = 4'h1;
      end
      5'h13: begin
        out_target = 4'h9;
        out_target1 = 4'h1;
      end
      5'h14: begin
        out_target = 4'h0;
        out_target1 = 4'h2;
      end
      5'h15: begin
        out_target = 4'h1;
        out_target1 = 4'h2;
      end
      5'h16: begin
        out_target = 4'h2;
        out_target1 = 4'h2;
      end
      5'h17: begin
        out_target = 4'h3;
        out_target1 = 4'h2;
      end
      5'h18: begin
        out_target = 4'h4;
        out_target1 = 4'h2;
      end
      5'h19: begin
        out_target = 4'h5;
        out_target1 = 4'h2;
      end
      5'h1a: begin
        out_target = 4'h6;
        out_target1 = 4'h2;
      end
      5'h1b: begin
        out_target = 4'h7;
        out_target1 = 4'h2;
      end
      5'h1c: begin
        out_target = 4'h8;
        out_target1 = 4'h2;
      end
      5'h1d: begin
        out_target = 4'h9;
        out_target1 = 4'h2;
      end
      5'h1e: begin
        out_target = 4'h0;
        out_target1 = 4'h3;
      end
      5'h1f: begin
        out_target = 4'h1;
        out_target1 = 4'h3;
      end
      6'h20: begin
        out_target = 4'h2;
        out_target1 = 4'h3;
      end
      6'h21: begin
        out_target = 4'h3;
        out_target1 = 4'h3;
      end
      6'h22: begin
        out_target = 4'h4;
        out_target1 = 4'h3;
      end
      6'h23: begin
        out_target = 4'h5;
        out_target1 = 4'h3;
      end
      6'h24: begin
        out_target = 4'h6;
        out_target1 = 4'h3;
      end
      6'h25: begin
        out_target = 4'h7;
        out_target1 = 4'h3;
      end
      6'h26: begin
        out_target = 4'h8;
        out_target1 = 4'h3;
      end
      6'h27: begin
        out_target = 4'h9;
        out_target1 = 4'h3;
      end
      6'h28: begin
        out_target = 4'h0;
        out_target1 = 4'h4;
      end
      6'h29: begin
        out_target = 4'h1;
        out_target1 = 4'h4;
      end
      6'h2a: begin
        out_target = 4'h2;
        out_target1 = 4'h4;
      end
      6'h2b: begin
        out_target = 4'h3;
        out_target1 = 4'h4;
      end
      6'h2c: begin
        out_target = 4'h4;
        out_target1 = 4'h4;
      end
      6'h2d: begin
        out_target = 4'h5;
        out_target1 = 4'h4;
      end
      6'h2e: begin
        out_target = 4'h6;
        out_target1 = 4'h4;
      end
      6'h2f: begin
        out_target = 4'h7;
        out_target1 = 4'h4;
      end
      6'h30: begin
        out_target = 4'h8;
        out_target1 = 4'h4;
      end
      6'h31: begin
        out_target = 4'h9;
        out_target1 = 4'h4;
      end
      6'h32: begin
        out_target = 4'h0;
        out_target1 = 4'h5;
      end
      6'h33: begin
        out_target = 4'h1;
        out_target1 = 4'h5;
      end
      6'h34: begin
        out_target = 4'h2;
        out_target1 = 4'h5;
      end
      6'h35: begin
        out_target = 4'h3;
        out_target1 = 4'h5;
      end
      6'h36: begin
        out_target = 4'h4;
        out_target1 = 4'h5;
      end
      6'h37: begin
        out_target = 4'h5;
        out_target1 = 4'h5;
      end
      6'h38: begin
        out_target = 4'h6;
        out_target1 = 4'h5;
      end
      6'h39: begin
        out_target = 4'h7;
        out_target1 = 4'h5;
      end
      6'h3a: begin
        out_target = 4'h8;
        out_target1 = 4'h5;
      end
      6'h3b: begin
        out_target = 4'h9;
        out_target1 = 4'h5;
      end
      6'h3c: begin
        out_target = 4'h0;
        out_target1 = 4'h6;
      end
      6'h3d: begin
        out_target = 4'h1;
        out_target1 = 4'h6;
      end
      6'h3e: begin
        out_target = 4'h2;
        out_target1 = 4'h6;
      end
      6'h3f: begin
        out_target = 4'h3;
        out_target1 = 4'h6;
      end
      7'h40: begin
        out_target = 4'h4;
        out_target1 = 4'h6;
      end
      7'h41: begin
        out_target = 4'h5;
        out_target1 = 4'h6;
      end
      7'h42: begin
        out_target = 4'h6;
        out_target1 = 4'h6;
      end
      7'h43: begin
        out_target = 4'h7;
        out_target1 = 4'h6;
      end
      7'h44: begin
        out_target = 4'h8;
        out_target1 = 4'h6;
      end
      7'h45: begin
        out_target = 4'h9;
        out_target1 = 4'h6;
      end
      7'h46: begin
        out_target = 4'h0;
        out_target1 = 4'h7;
      end
      7'h47: begin
        out_target = 4'h1;
        out_target1 = 4'h7;
      end
      7'h48: begin
        out_target = 4'h2;
        out_target1 = 4'h7;
      end
      7'h49: begin
        out_target = 4'h3;
        out_target1 = 4'h7;
      end
      7'h4a: begin
        out_target = 4'h4;
        out_target1 = 4'h7;
      end
      7'h4b: begin
        out_target = 4'h5;
        out_target1 = 4'h7;
      end
      7'h4c: begin
        out_target = 4'h6;
        out_target1 = 4'h7;
      end
      7'h4d: begin
        out_target = 4'h7;
        out_target1 = 4'h7;
      end
      7'h4e: begin
        out_target = 4'h8;
        out_target1 = 4'h7;
      end
      7'h4f: begin
        out_target = 4'h9;
        out_target1 = 4'h7;
      end
      7'h50: begin
        out_target = 4'h0;
        out_target1 = 4'h8;
      end
      7'h51: begin
        out_target = 4'h1;
        out_target1 = 4'h8;
      end
      7'h52: begin
        out_target = 4'h2;
        out_target1 = 4'h8;
      end
      7'h53: begin
        out_target = 4'h3;
        out_target1 = 4'h8;
      end
      7'h54: begin
        out_target = 4'h4;
        out_target1 = 4'h8;
      end
      7'h55: begin
        out_target = 4'h5;
        out_target1 = 4'h8;
      end
      7'h56: begin
        out_target = 4'h6;
        out_target1 = 4'h8;
      end
      7'h57: begin
        out_target = 4'h7;
        out_target1 = 4'h8;
      end
      7'h58: begin
        out_target = 4'h8;
        out_target1 = 4'h8;
      end
      7'h59: begin
        out_target = 4'h9;
        out_target1 = 4'h8;
      end
      7'h5a: begin
        out_target = 4'h0;
        out_target1 = 4'h9;
      end
      7'h5b: begin
        out_target = 4'h1;
        out_target1 = 4'h9;
      end
      7'h5c: begin
        out_target = 4'h2;
        out_target1 = 4'h9;
      end
      7'h5d: begin
        out_target = 4'h3;
        out_target1 = 4'h9;
      end
      7'h5e: begin
        out_target = 4'h4;
        out_target1 = 4'h9;
      end
      7'h5f: begin
        out_target = 4'h5;
        out_target1 = 4'h9;
      end
      7'h60: begin
        out_target = 4'h6;
        out_target1 = 4'h9;
      end
      7'h61: begin
        out_target = 4'h7;
        out_target1 = 4'h9;
      end
      7'h62: begin
        out_target = 4'h8;
        out_target1 = 4'h9;
      end
      7'h63: begin
        out_target = 4'h9;
        out_target1 = 4'h9;
      end
      default: begin
        out_target = 4'h3;
        out_target1 = 4'h2;
      end
    endcase
  end
endmodule
